"use client";

import { useEffect,useState } from "react";
type Log={_id:string;phone:string;message:string;status:string;createdAt:string};
export default function SmsManager(){
 const [items,setItems]=useState<Log[]>([]);const [configured,setConfigured]=useState(false);const [sender,setSender]=useState("");const [balance,setBalance]=useState<number|null>(null);const [balanceOk,setBalanceOk]=useState(false);const [phone,setPhone]=useState("");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);const [notice,setNotice]=useState("");
 async function load(){const r=await fetch("/api/admin/sms",{cache:"no-store"});const d=await r.json();if(r.ok){setItems(d.items||[]);setConfigured(Boolean(d.configured));setSender(d.sender||"");setBalance(typeof d.balance==="number"?d.balance:null);setBalanceOk(Boolean(d.balanceOk))}}
 useEffect(()=>{load()},[]);
 async function send(e:React.FormEvent){e.preventDefault();setBusy(true);setNotice("");const r=await fetch("/api/admin/sms",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({phone,message})});const d=await r.json().catch(()=>({}));setBusy(false);if(!r.ok){setNotice(d.message||"გაგზავნა ვერ მოხერხდა.");await load();return}setPhone("");setMessage("");setNotice("SMS წარმატებით გაიგზავნა.");await load()}
 return <>
  <div className="adm-page-head"><div><h1>SMS ჟურნალი</h1><p>GoSMS-ის ავტომატური booking შეტყობინებები, ხელით გაგზავნა და ბალანსის კონტროლი.</p></div></div>
  <div className="adm-grid two">
   <section className="adm-card adm-card-pad"><div className="adm-card-title" style={{padding:0,paddingBottom:16,marginBottom:18}}><div><h2>SMS-ის გაგზავნა</h2><p>{configured?`GoSMS აქტიურია${sender?` • Sender: ${sender}`:""}`:"GoSMS ჯერ არ არის კონფიგურირებული"}</p></div><span className={`adm-badge ${configured?"":"warn"}`}>{configured?"აქტიური":"საჭიროა კონფიგურაცია"}</span></div><form className="adm-form" onSubmit={send}><div className="adm-field"><span>ტელეფონი</span><input inputMode="numeric" maxLength={9} placeholder="5XX XX XX XX" value={phone} onChange={e=>setPhone(e.target.value.replace(/\D/g,"").slice(0,9))}/></div><div className="adm-field"><span>ტექსტი</span><textarea maxLength={500} placeholder="შეტყობინების ტექსტი" value={message} onChange={e=>setMessage(e.target.value)}/></div><small style={{color:"var(--adm-muted)",fontSize:9}}>{message.length}/500 სიმბოლო</small>{notice&&<div className={`adm-notice ${notice.includes("ვერ")||notice.includes("არ არის")||notice.includes("არასწორია")?"error":""}`}>{notice}</div>}<button className="adm-btn primary" disabled={busy||!configured}>{busy?"იგზავნება...":"SMS-ის გაგზავნა"}</button></form></section>
   <section className="adm-card adm-card-pad"><h3 style={{marginTop:0}}>ინტეგრაციის სტატუსი</h3><p style={{color:"var(--adm-muted)",fontSize:11,lineHeight:1.75}}>ჯავშნის შექმნისას confirmation SMS ავტომატურად იგზავნება. API key და Sender მხოლოდ Vercel Environment Variables-ში ინახება და ბრაუზერში არ ჩანს.</p><div className={`adm-notice ${configured?"":"warn"}`}>{configured?"GoSMS კონფიგურაცია აღმოჩენილია.":"Vercel-ში დაამატეთ GOSMS_API_KEY და GOSMS_SENDER."}</div>{configured&&<div style={{marginTop:12,display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}><div className="adm-stat-v2"><span>Sender</span><strong style={{fontSize:16}}>{sender||"—"}</strong></div><div className="adm-stat-v2"><span>SMS ბალანსი</span><strong style={{fontSize:16}}>{balanceOk&&balance!==null?balance:"ვერ შემოწმდა"}</strong></div></div>}</section>
  </div>
  <section className="adm-card" style={{marginTop:18}}><div className="adm-card-title"><div><h2>ბოლო შეტყობინებები</h2><p>ბოლო {items.length} ჩანაწერი</p></div><button className="adm-btn" onClick={load}>განახლება</button></div><div className="adm-table-wrap"><table className="adm-table-v2"><thead><tr><th>დრო</th><th>ნომერი</th><th>ტექსტი</th><th>სტატუსი</th></tr></thead><tbody>{items.map(x=><tr key={x._id}><td>{new Date(x.createdAt).toLocaleString("ka-GE")}</td><td><strong>{x.phone}</strong></td><td style={{maxWidth:520}}>{x.message}</td><td><span className={`adm-badge ${x.status==="failed"?"danger":x.status==="skipped"?"warn":""}`}>{x.status==="sent"?"გაგზავნილი":x.status==="failed"?"შეცდომა":"გამოტოვებული"}</span></td></tr>)}</tbody></table>{items.length===0&&<div className="adm-empty-v2">SMS ისტორია ჯერ ცარიელია.</div>}</div></section>
 </>
}
